### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by c0d3rman** [c0d3rman/Impromptu.js#1]
- [ ] Refine magic dict access - e.g. initialization of values
- [ ] Make server bypass its own client for reduced lag
- [ ] Write proper logic for getting back to a stable magic dict state when the server changes
- [ ] Bundle peerjs
- [ ] Issue initial storage update
- [ ] Separate client and server into different classes (also makes it easier to make a pseudo-client)
